# Generated by Django 4.2.3 on 2023-11-11 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=7)),
                ('pref', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('claimant_number', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.address', verbose_name='住所')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_order_no', models.CharField(max_length=200, verbose_name='注文番号')),
                ('business_desc', models.CharField(max_length=200, verbose_name='業務名称')),
                ('due_date', models.DateField(verbose_name='締日')),
                ('payment_date', models.DateField(verbose_name='支払予定日')),
                ('note', models.CharField(max_length=200, verbose_name='備考')),
                ('status', models.IntegerField(verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='OSCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.company')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='単価名称')),
                ('base_price', models.IntegerField(verbose_name='月額単価')),
                ('deduct_price', models.IntegerField(verbose_name='超過単価')),
                ('excess_price', models.IntegerField(verbose_name='控除単価')),
                ('base_work_hour', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='基準労働時間')),
                ('max_work_hour', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='上限時間')),
                ('min_work_hour', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='下限時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='単価名称')),
                ('start_date', models.DateField(verbose_name='作業開始日')),
                ('end_date', models.DateField(verbose_name='作業終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Worktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hour', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='作業時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.person', verbose_name='要員')),
                ('span', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.span', verbose_name='作業期間')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.order', verbose_name='受注')),
                ('worktime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.worktime', verbose_name='作業時間')),
            ],
        ),
        migrations.CreateModel(
            name='R_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_order_no', models.CharField(max_length=200, verbose_name='注文番号')),
                ('business_desc', models.CharField(max_length=200, verbose_name='業務名称')),
                ('due_date', models.DateField(verbose_name='締日')),
                ('payment_date', models.DateField(verbose_name='支払予定日')),
                ('note', models.CharField(max_length=200, verbose_name='備考')),
                ('status', models.IntegerField(verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.company', verbose_name='受注元')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.person', verbose_name='要員')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.price', verbose_name='単価')),
                ('span', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.span', verbose_name='作業期間')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名称')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.company')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='associated_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.r_order', verbose_name='受注データ'),
        ),
        migrations.AddField(
            model_name='order',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.person', verbose_name='要員'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.price', verbose_name='単価'),
        ),
        migrations.AddField(
            model_name='order',
            name='span',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.span', verbose_name='作業期間'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.company', verbose_name='発注先'),
        ),
        migrations.CreateModel(
            name='Effort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField(verbose_name='対象年月')),
                ('budget_effort', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='計画工数')),
                ('actual_effort', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='実績工数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.project')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField(verbose_name='対象年月')),
                ('cost_price', models.IntegerField(verbose_name='原価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.person')),
            ],
        ),
    ]
